drop table if exists owner CASCADE;
create table owner (
                       id bigint generated by default as identity,
                       name varchar(255),
                       primary key (id)
);