drop table if exists animal CASCADE;
create table animal (
                        id bigint generated by default as identity,
                        name varchar(255),
                        owner_id bigint,
                        vet_id bigint,
                        primary key (id)
);
alter table animal
    add constraint FKojllrs4g1np633u6beb3hnk74
        foreign key (owner_id)
            references owner;
alter table animal
    add constraint FKe2rvpcd6ev5qdx2iwjbu6mh2r
        foreign key (vet_id)
            references vet;